services:
  web:
    container_name: chessclub-web-1
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DATABASE_URI=sqlite:////app/instance/chessclub.db
    volumes:
      - db-data:/app/instance
      - ./watched_clubs.json:/app/watched_clubs.json

volumes:
  db-data:
